name: Report a Bug (NeoForge)
description: File a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a Bug in BetterEnd (NeoForge)!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Versions

  - type: input
    id: bn_version
    attributes:
      label: BetterEnd (NeoForge)
      description: What version of BetterEnd are you running?
      placeholder: 21.0.x
    validations:
      required: true

  - type: input
    id: bclib_version
    attributes:
      label: BCLib (NeoForge)
      description: What version of BCLib are you running?
      placeholder: 21.0.x
    validations:
      required: true

  - type: input
    id: wover_version
    attributes:
      label: WorldWeaver (NeoForge)
      description: What version of WorldWeaver are you running?
      placeholder: 21.0.x
    validations:
      required: true

  - type: input
    id: neoforge_version
    attributes:
      label: NeoForge
      description: What version of NeoForge are you using?
      placeholder: 21.x.x
    validations:
      required: true

  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft
      description: What version of Minecraft is installed?
      options:
        - "1.21.1"
        - "1.21"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additional Information

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: other_mods
    attributes:
      label: Other Mods
      description: If you can, please supply a list of installed Mods (besides BetterEnd, BCLib, and WorldWeaver). This information may already be included in the log above.
      render: shell
