package org.betterx.datagen.betterend.recipes;

import org.betterx.betterend.recipe.builders.InfusionRecipe;
import org.betterx.betterend.registry.EndBlocks;
import org.betterx.betterend.registry.EndItems;
import org.betterx.wover.core.api.ModCore;
import org.betterx.wover.datagen.api.provider.WoverRecipeProvider;

import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.recipes.RecipeOutput;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.block.Blocks;

public class InfusionRecipesProvider extends WoverRecipeProvider {
    public InfusionRecipesProvider(ModCore modCore) {
        super(modCore, "BetterEnd - Infusion Recipes");
    }

    public void bootstrap(HolderLookup.Provider provider, RecipeOutput context) {
        final HolderLookup.RegistryLookup<Enchantment> enchantments = provider.lookupOrThrow(Registries.ENCHANTMENT);
        InfusionRecipe.create("runed_flavolite", EndBlocks.FLAVOLITE_RUNED)
                      .setPrimaryInput(EndBlocks.FLAVOLITE.polished)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(100)
                      .build(context);

        InfusionRecipe.create("eternal_crystal", EndItems.ETERNAL_CRYSTAL)
                      .setPrimaryInputAndUnlock(Items.END_CRYSTAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, EndItems.ENDER_SHARD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, EndItems.ENDER_SHARD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, EndItems.ENDER_SHARD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, EndItems.ENDER_SHARD)
                      .setTime(250)
                      .build(context);

        InfusionRecipe.create("crystalite_helmet", EndItems.CRYSTALITE_HELMET)
                      .setPrimaryInputAndUnlock(EndBlocks.TERMINITE.helmet)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(150)
                      .build(context);
        InfusionRecipe.create("crystalite_chestplate", EndItems.CRYSTALITE_CHESTPLATE)
                      .setPrimaryInputAndUnlock(EndBlocks.TERMINITE.chestplate)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("crystalite_leggings", EndItems.CRYSTALITE_LEGGINGS)
                      .setPrimaryInputAndUnlock(EndBlocks.TERMINITE.leggings)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(225)
                      .build(context);
        InfusionRecipe.create("crystalite_boots", EndItems.CRYSTALITE_BOOTS)
                      .setPrimaryInputAndUnlock(EndBlocks.TERMINITE.boots)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(150)
                      .build(context);

        InfusionRecipe.create("crystalite_elytra", EndItems.CRYSTALITE_ELYTRA)
                      .setPrimaryInputAndUnlock(Items.ELYTRA)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.ENCHANTED_MEMBRANE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.ENCHANTED_MEMBRANE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.ENCHANTED_MEMBRANE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(500)
                      .build(context);

        InfusionRecipe.create("enchanted_petal", EndItems.ENCHANTED_PETAL)
                      .setPrimaryInputAndUnlock(EndItems.HYDRALUX_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(75)
                      .build(context);
        InfusionRecipe.create("enchanted_membrane", EndItems.ENCHANTED_MEMBRANE)
                      .setPrimaryInputAndUnlock(Items.PHANTOM_MEMBRANE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(75)
                      .build(context);

        InfusionRecipe.create("protection_book", Enchantments.PROTECTION, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.TURTLE_HELMET)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("fire_protection_book", Enchantments.FIRE_PROTECTION, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.BLAZE_ROD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.BLAZE_ROD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.BLAZE_ROD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create(
                              "feather_falling_book",
                              Enchantments.FEATHER_FALLING, 1, enchantments
                      )
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.FEATHER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.FEATHER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.FEATHER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create(
                              "blast_protection_book",
                              Enchantments.BLAST_PROTECTION, 1, enchantments
                      )
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Blocks.OBSIDIAN)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Blocks.OBSIDIAN)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Blocks.OBSIDIAN)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create(
                              "projectile_protection_book",
                              Enchantments.PROJECTILE_PROTECTION, 1, enchantments
                      )
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.TURTLE_SCUTE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.SHIELD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.TURTLE_SCUTE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("respiration_book", Enchantments.RESPIRATION, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.NAUTILUS_SHELL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.NAUTILUS_SHELL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.NAUTILUS_SHELL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("aqua_affinity_book", Enchantments.AQUA_AFFINITY, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.PRISMARINE_CRYSTALS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.PRISMARINE_CRYSTALS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.PRISMARINE_CRYSTALS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("thorns_book", Enchantments.THORNS, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Blocks.CACTUS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Blocks.CACTUS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Blocks.CACTUS)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("depth_strider_book", Enchantments.DEPTH_STRIDER, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Blocks.LILY_PAD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndBlocks.END_LILY_SEED)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Blocks.LILY_PAD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("frost_walker_book", Enchantments.FROST_WALKER, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndBlocks.ANCIENT_EMERALD_ICE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("soul_speed_book", Enchantments.SOUL_SPEED, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("swift_sneak_book", Enchantments.SWIFT_SNEAK, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ETERNAL_CRYSTAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.SCULK_SENSOR)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.SCULK_CATALYST)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.SCULK_SENSOR)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.SCULK_VEIN)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.SCULK_VEIN)
                      .group("enchantment")
                      .setTime(500)
                      .build(context);
        InfusionRecipe.create("sharpness_book", Enchantments.SHARPNESS, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.NETHERITE_SCRAP)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("smite_book", Enchantments.SMITE, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Blocks.SUNFLOWER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.GOLD_INGOT)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Blocks.SUNFLOWER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("bane_of_arthropods_book", Enchantments.BANE_OF_ARTHROPODS, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.FERMENTED_SPIDER_EYE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.IRON_INGOT)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.FERMENTED_SPIDER_EYE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("knockback_book", Enchantments.KNOCKBACK, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.REDSTONE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Blocks.PISTON)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.REDSTONE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("fire_aspect_book", Enchantments.FIRE_ASPECT, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.BLAZE_POWDER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.MAGMA_CREAM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.BLAZE_POWDER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("looting_book", Enchantments.LOOTING, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.GOLD_INGOT)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("sweeping_book", Enchantments.SWEEPING_EDGE, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.GOLDEN_SWORD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.IRON_SWORD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.GOLDEN_SWORD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("efficiency_book", Enchantments.EFFICIENCY, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("silk_touch_book", Enchantments.SILK_TOUCH, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Blocks.COBWEB)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.ETERNAL_CRYSTAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Blocks.COBWEB)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(375)
                      .build(context);
        InfusionRecipe.create("unbreaking_book", Enchantments.UNBREAKING, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.DIAMOND)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.DIAMOND)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.DIAMOND)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("fortune_book", Enchantments.FORTUNE, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.RABBIT_FOOT)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("power_book", Enchantments.POWER, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.DIAMOND_SWORD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("punch_book", Enchantments.PUNCH, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.POPPED_CHORUS_FRUIT)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.POPPED_CHORUS_FRUIT)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("flame_book", Enchantments.FLAME, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.BLAZE_POWDER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.BLAZE_POWDER)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("infinity_book", Enchantments.INFINITY, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, EndItems.ETERNAL_CRYSTAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(375)
                      .build(context);
        InfusionRecipe.create("luck_of_sea_book", Enchantments.LUCK_OF_THE_SEA, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.FISHING_ROD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("lure_book", Enchantments.LURE, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.GOLD_NUGGET)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.FISHING_ROD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.GOLD_NUGGET)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("loyalty_book", Enchantments.LOYALTY, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.ENDER_EYE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.HEART_OF_THE_SEA)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.ENDER_EYE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(375)
                      .build(context);
        InfusionRecipe.create("impaling_book", Enchantments.IMPALING, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.PRISMARINE_SHARD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.IRON_SWORD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.PRISMARINE_SHARD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("riptide_book", Enchantments.RIPTIDE, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.LEAD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.HEART_OF_THE_SEA)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.LEAD)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(375)
                      .build(context);
        InfusionRecipe.create("channeling_book", Enchantments.CHANNELING, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.CHAIN)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.HEART_OF_THE_SEA)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.CHAIN)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(375)
                      .build(context);
        InfusionRecipe.create("multishot_book", Enchantments.MULTISHOT, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.ARROW)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.ARROW)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("quick_charge_book", Enchantments.QUICK_CHARGE, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.QUARTZ)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.GLOWSTONE_DUST)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.QUARTZ)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("piercing_book", Enchantments.PIERCING, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.GLOWSTONE_DUST)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.GLOWSTONE_DUST)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(300)
                      .build(context);
        InfusionRecipe.create("mending_book", Enchantments.MENDING, 1, enchantments)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.EAST, Items.EXPERIENCE_BOTTLE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH, Blocks.ANVIL)
                      .addCatalyst(InfusionRecipe.CatalystSlot.WEST, Items.EXPERIENCE_BOTTLE)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.CatalystSlot.NORTH_WEST, Items.LAPIS_LAZULI)
                      .group("enchantment")
                      .setTime(375)
                      .build(context);
    }

}
